version: "3.9"

services:
  backend:
    build:
      context: ./back
      dockerfile: Dockerfile
    env_file:
      - ./back/.env.prod
    ports:
      - "3000:3000"
    depends_on:
      - redis

  frontend:
    build:
      context: ./front
      dockerfile: Dockerfile
    env_file:
      - ./front/.env.prod
    ports:
      - "80:80"
    depends_on:
      - backend

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
