services:
  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: oclaris
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports: ["55432:5432"]
    volumes: ["pgdata:/var/lib/postgresql/data"]
  redis:
    image: redis:7-alpine
    ports: ["6379:6379"]
volumes:
  pgdata: {}