server {
    listen 80;
    server_name _;

    root /usr/share/nginx/html;
    index index.html;

    # 👉 Important : toutes les routes du front renvoient index.html
    location / {
        try_files $uri $uri/ /index.html;
    }

    # Les assets (JS/CSS/etc.)
    location /assets/ {
        try_files $uri =404;
    }
}
